Server = "sim.smogon.com"
Port = "8000"
Nick = "bot_nick"
Password = "iluvroseyraid"
MessagesPerSecond = 3.0
Rooms = ["techcode"] # The rooms you want to bot to join
Avatar = "0" # Set to "0" to get a default avatar, up to "294"
PluginPrefixes = ["."]
